name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: '@pleaseai/config'

      # Publish to npm when a release is created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: oven-sh/setup-bun@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          bun-version: latest

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: bun install

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: bun run build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm publish --access public
